# fly.toml app configuration file generated for hearchco-frontend on 2023-12-03T17:09:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hearchco-frontend"
primary_region = "cdg"

[build]
  image = "ghcr.io/hearchco/frontend:latest"

[env]
  API_URL = "http://hearchco.flycast"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 20
    soft_limit = 10

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"
